improve build script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1255,8 +1255,8 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-python         make python module
-  --enable-R              make R package
+  --enable-python         make python module (default is disabled)
+  --enable-R              make R package (default is disabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -4154,7 +4154,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -4175,7 +4175,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -4632,14 +4632,14 @@ fi
 
 if test "x$pass" == "xno"
 then
-	{ { echo "$as_me:$LINENO: error: cannot find header file gc.h. Consider setting --with-libgc-include=PATH_TO_LIBGC_LIB_DIR" >&5
-echo "$as_me: error: cannot find header file gc.h. Consider setting --with-libgc-include=PATH_TO_LIBGC_LIB_DIR" >&2;}
+	{ { echo "$as_me:$LINENO: error: cannot find header file gc.h. Consider setting --with-libgc-include=PATH_TO_LIBGC_INCLUDE_DIR" >&5
+echo "$as_me: error: cannot find header file gc.h. Consider setting --with-libgc-include=PATH_TO_LIBGC_INCLUDE_DIR" >&2;}
    { (exit 1); exit 1; }; }
 else
 	if test "x$pass" == "xno-reset"
 	then
-		{ { echo "$as_me:$LINENO: error: cannot find header file gc.h. Consider resetting --with-libgc-include=PATH_TO_LIBGC_LIB_DIR" >&5
-echo "$as_me: error: cannot find header file gc.h. Consider resetting --with-libgc-include=PATH_TO_LIBGC_LIB_DIR" >&2;}
+		{ { echo "$as_me:$LINENO: error: cannot find header file gc.h. Consider resetting --with-libgc-include=PATH_TO_LIBGC_INCLUDE_DIR" >&5
+echo "$as_me: error: cannot find header file gc.h. Consider resetting --with-libgc-include=PATH_TO_LIBGC_INCLUDE_DIR" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi
@@ -4907,7 +4907,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -4928,7 +4928,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
